# Generated by Django 2.0.4 on 2018-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhoisTbotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('domain', models.CharField(max_length=256)),
                ('last_notif_date', models.DateTimeField()),
                ('exp_date', models.DateTimeField()),
            ],
        ),
    ]
